# docker-compose.yml
services:
  db:
    build: ./clea-db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vectordb
    networks:
      - clea-network

  api:
    build: ./clea-api
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=vectordb
      - TORCH_DEVICE=cuda
      - FRONTEND_URLS=http://localhost:8888
      - ALLOW_ALL_ORIGINS=true
      - COMPOSE_BAKE=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - EMBEDDING_MODEL="almanach/camembertav2-base"
      - CROSS_ENCODER_MODEL="cross-encoder/mmarco-mMiniLMv2-L12-H384-v1"
      - LLM_MODEL="Qwen/Qwen3-0.6B"
    networks:
      - clea-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  webui:
    build: 
      context: ./clea-webui
    depends_on:
      - api
    environment:
      - NODE_ENV=production
      - PUBLIC_API_URL=http://localhost:8888/api
    networks:
      - clea-network

  nginx:
    build: ./clea-nginx
    ports:
      - "8888:8888"
    depends_on:
      - api
      - webui
    networks:
      - clea-network

networks:
  clea-network:

volumes:
  db_data: